import "./globals.css";

import localFont from "next/font/local";

import Navbar from "./components/Navbar";
import { ThemeProvider } from "./providers/ThemeProvider";

import type { Metadata } from "next";

const geistSans = localFont({
  weight: "100 900",
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  weight: "100 900",
  variable: "--font-geist-mono",
  src: "./fonts/GeistMonoVF.woff",
});

export const metadata: Metadata = {
  title: "Hacker News V2",
  description: "Generated by Omkar Narayankar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <main className="container mx-auto px-4 py-8">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
